// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"os"
	"transcription-service/controller/healthcontroller"
	"transcription-service/router"
)

// Injectors from Wire.go:

func InitializeServer() (*Server, error) {
	engine := NewGinEngine()
	controller := healthcontroller.New()
	routerRouter := router.New(engine, controller)
	server := New(engine, routerRouter)
	return server, nil
}

// Wire.go:

func NewGinEngine() *gin.Engine {
	gin.SetMode(os.Getenv("GIN_MODE"))

	return gin.New()
}

var ProviderSet = wire.NewSet(
	NewGinEngine,
	New, router.New, healthcontroller.New,
)
