// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"os"
	"transcription-service/controller/healthcontroller"
	"transcription-service/controller/transcribercontroller"
	"transcription-service/domain/persistance"
	"transcription-service/domain/transcriber"
	"transcription-service/internal/config"
	"transcription-service/internal/router"
	"transcription-service/pkg/faster-whisper"
	"transcription-service/pkg/minio"
	"transcription-service/pkg/postgres"
	"transcription-service/usecase/transcription"
)

// Injectors from Wire.go:

func InitializeServer() (*Server, error) {
	engine := NewGinEngine()
	controller := healthcontroller.New()
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	storage, err := minio.New(configConfig)
	if err != nil {
		return nil, err
	}
	transcriptionRepository, err := postgres.New(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := fasterwhisper.New(configConfig)
	if err != nil {
		return nil, err
	}
	useCase := transcription.New(storage, transcriptionRepository, client, configConfig)
	transcribercontrollerController := transcribercontroller.New(useCase)
	routerRouter := router.New(engine, controller, transcribercontrollerController)
	server := New(engine, routerRouter, transcriptionRepository)
	return server, nil
}

// Wire.go:

func NewGinEngine() *gin.Engine {
	gin.SetMode(os.Getenv("GIN_MODE"))

	return gin.New()
}

var ProviderSet = wire.NewSet(wire.Bind(new(persistance.Storage), new(*minio.Storage)), wire.Bind(new(transcriber.Transcriber), new(*fasterwhisper.Client)), NewGinEngine,
	New, transcription.New, healthcontroller.New, transcribercontroller.New, router.New, minio.New, fasterwhisper.New, postgres.New, config.New,
)
