// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"transcription-service/domain/transcriptionentity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTranscriptionRepository creates a new instance of MockTranscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranscriptionRepository {
	mock := &MockTranscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranscriptionRepository is an autogenerated mock type for the TranscriptionRepository type
type MockTranscriptionRepository struct {
	mock.Mock
}

type MockTranscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranscriptionRepository) EXPECT() *MockTranscriptionRepository_Expecter {
	return &MockTranscriptionRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockTranscriptionRepository
func (_mock *MockTranscriptionRepository) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTranscriptionRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTranscriptionRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTranscriptionRepository_Expecter) Close() *MockTranscriptionRepository_Close_Call {
	return &MockTranscriptionRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTranscriptionRepository_Close_Call) Run(run func()) *MockTranscriptionRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTranscriptionRepository_Close_Call) Return(err error) *MockTranscriptionRepository_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTranscriptionRepository_Close_Call) RunAndReturn(run func() error) *MockTranscriptionRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function for the type MockTranscriptionRepository
func (_mock *MockTranscriptionRepository) GetAllByUserID(userID string) ([]*transcriptionentity.Transcription, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []*transcriptionentity.Transcription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*transcriptionentity.Transcription, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*transcriptionentity.Transcription); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*transcriptionentity.Transcription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranscriptionRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockTranscriptionRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockTranscriptionRepository_Expecter) GetAllByUserID(userID interface{}) *MockTranscriptionRepository_GetAllByUserID_Call {
	return &MockTranscriptionRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID)}
}

func (_c *MockTranscriptionRepository_GetAllByUserID_Call) Run(run func(userID string)) *MockTranscriptionRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranscriptionRepository_GetAllByUserID_Call) Return(transcriptions []*transcriptionentity.Transcription, err error) *MockTranscriptionRepository_GetAllByUserID_Call {
	_c.Call.Return(transcriptions, err)
	return _c
}

func (_c *MockTranscriptionRepository_GetAllByUserID_Call) RunAndReturn(run func(userID string) ([]*transcriptionentity.Transcription, error)) *MockTranscriptionRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTranscriptionRepository
func (_mock *MockTranscriptionRepository) GetByID(id string) (*transcriptionentity.Transcription, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *transcriptionentity.Transcription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*transcriptionentity.Transcription, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *transcriptionentity.Transcription); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transcriptionentity.Transcription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranscriptionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTranscriptionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id string
func (_e *MockTranscriptionRepository_Expecter) GetByID(id interface{}) *MockTranscriptionRepository_GetByID_Call {
	return &MockTranscriptionRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockTranscriptionRepository_GetByID_Call) Run(run func(id string)) *MockTranscriptionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranscriptionRepository_GetByID_Call) Return(transcription *transcriptionentity.Transcription, err error) *MockTranscriptionRepository_GetByID_Call {
	_c.Call.Return(transcription, err)
	return _c
}

func (_c *MockTranscriptionRepository_GetByID_Call) RunAndReturn(run func(id string) (*transcriptionentity.Transcription, error)) *MockTranscriptionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTranscriptionRepository
func (_mock *MockTranscriptionRepository) Save(transcription *transcriptionentity.Transcription) error {
	ret := _mock.Called(transcription)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*transcriptionentity.Transcription) error); ok {
		r0 = returnFunc(transcription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTranscriptionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTranscriptionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - transcription *transcriptionentity.Transcription
func (_e *MockTranscriptionRepository_Expecter) Save(transcription interface{}) *MockTranscriptionRepository_Save_Call {
	return &MockTranscriptionRepository_Save_Call{Call: _e.mock.On("Save", transcription)}
}

func (_c *MockTranscriptionRepository_Save_Call) Run(run func(transcription *transcriptionentity.Transcription)) *MockTranscriptionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *transcriptionentity.Transcription
		if args[0] != nil {
			arg0 = args[0].(*transcriptionentity.Transcription)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranscriptionRepository_Save_Call) Return(err error) *MockTranscriptionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTranscriptionRepository_Save_Call) RunAndReturn(run func(transcription *transcriptionentity.Transcription) error) *MockTranscriptionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTranscription provides a mock function for the type MockTranscriptionRepository
func (_mock *MockTranscriptionRepository) UpdateWithTranscription(transcription *transcriptionentity.Transcription) error {
	ret := _mock.Called(transcription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTranscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*transcriptionentity.Transcription) error); ok {
		r0 = returnFunc(transcription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTranscriptionRepository_UpdateWithTranscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTranscription'
type MockTranscriptionRepository_UpdateWithTranscription_Call struct {
	*mock.Call
}

// UpdateWithTranscription is a helper method to define mock.On call
//   - transcription *transcriptionentity.Transcription
func (_e *MockTranscriptionRepository_Expecter) UpdateWithTranscription(transcription interface{}) *MockTranscriptionRepository_UpdateWithTranscription_Call {
	return &MockTranscriptionRepository_UpdateWithTranscription_Call{Call: _e.mock.On("UpdateWithTranscription", transcription)}
}

func (_c *MockTranscriptionRepository_UpdateWithTranscription_Call) Run(run func(transcription *transcriptionentity.Transcription)) *MockTranscriptionRepository_UpdateWithTranscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *transcriptionentity.Transcription
		if args[0] != nil {
			arg0 = args[0].(*transcriptionentity.Transcription)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranscriptionRepository_UpdateWithTranscription_Call) Return(err error) *MockTranscriptionRepository_UpdateWithTranscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTranscriptionRepository_UpdateWithTranscription_Call) RunAndReturn(run func(transcription *transcriptionentity.Transcription) error) *MockTranscriptionRepository_UpdateWithTranscription_Call {
	_c.Call.Return(run)
	return _c
}
