// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteFile(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockStorage_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - path string
func (_e *MockStorage_Expecter) DeleteFile(path interface{}) *MockStorage_DeleteFile_Call {
	return &MockStorage_DeleteFile_Call{Call: _e.mock.On("DeleteFile", path)}
}

func (_c *MockStorage_DeleteFile_Call) Run(run func(path string)) *MockStorage_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteFile_Call) Return(err error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteFile_Call) RunAndReturn(run func(path string) error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockStorage
func (_mock *MockStorage) GetFile(path string) ([]byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockStorage_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - path string
func (_e *MockStorage_Expecter) GetFile(path interface{}) *MockStorage_GetFile_Call {
	return &MockStorage_GetFile_Call{Call: _e.mock.On("GetFile", path)}
}

func (_c *MockStorage_GetFile_Call) Run(run func(path string)) *MockStorage_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_GetFile_Call) Return(bytes []byte, err error) *MockStorage_GetFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockStorage_GetFile_Call) RunAndReturn(run func(path string) ([]byte, error)) *MockStorage_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// StoreFile provides a mock function for the type MockStorage
func (_mock *MockStorage) StoreFile(path string, data []byte) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for StoreFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_StoreFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreFile'
type MockStorage_StoreFile_Call struct {
	*mock.Call
}

// StoreFile is a helper method to define mock.On call
//   - path string
//   - data []byte
func (_e *MockStorage_Expecter) StoreFile(path interface{}, data interface{}) *MockStorage_StoreFile_Call {
	return &MockStorage_StoreFile_Call{Call: _e.mock.On("StoreFile", path, data)}
}

func (_c *MockStorage_StoreFile_Call) Run(run func(path string, data []byte)) *MockStorage_StoreFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_StoreFile_Call) Return(err error) *MockStorage_StoreFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_StoreFile_Call) RunAndReturn(run func(path string, data []byte) error) *MockStorage_StoreFile_Call {
	_c.Call.Return(run)
	return _c
}
