// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"transcription-service/domain/transcriber"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTranscriber creates a new instance of MockTranscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranscriber {
	mock := &MockTranscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranscriber is an autogenerated mock type for the Transcriber type
type MockTranscriber struct {
	mock.Mock
}

type MockTranscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranscriber) EXPECT() *MockTranscriber_Expecter {
	return &MockTranscriber_Expecter{mock: &_m.Mock}
}

// Transcribe provides a mock function for the type MockTranscriber
func (_mock *MockTranscriber) Transcribe(req transcriber.TranscriptionRequest) (*transcriber.TranscriptionResponse, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Transcribe")
	}

	var r0 *transcriber.TranscriptionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(transcriber.TranscriptionRequest) (*transcriber.TranscriptionResponse, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(transcriber.TranscriptionRequest) *transcriber.TranscriptionResponse); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transcriber.TranscriptionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(transcriber.TranscriptionRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranscriber_Transcribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcribe'
type MockTranscriber_Transcribe_Call struct {
	*mock.Call
}

// Transcribe is a helper method to define mock.On call
//   - req transcriber.TranscriptionRequest
func (_e *MockTranscriber_Expecter) Transcribe(req interface{}) *MockTranscriber_Transcribe_Call {
	return &MockTranscriber_Transcribe_Call{Call: _e.mock.On("Transcribe", req)}
}

func (_c *MockTranscriber_Transcribe_Call) Run(run func(req transcriber.TranscriptionRequest)) *MockTranscriber_Transcribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 transcriber.TranscriptionRequest
		if args[0] != nil {
			arg0 = args[0].(transcriber.TranscriptionRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranscriber_Transcribe_Call) Return(transcriptionResponse *transcriber.TranscriptionResponse, err error) *MockTranscriber_Transcribe_Call {
	_c.Call.Return(transcriptionResponse, err)
	return _c
}

func (_c *MockTranscriber_Transcribe_Call) RunAndReturn(run func(req transcriber.TranscriptionRequest) (*transcriber.TranscriptionResponse, error)) *MockTranscriber_Transcribe_Call {
	_c.Call.Return(run)
	return _c
}
